language: c
before_install:
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
#  - sleep 3
#  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/AskSinPP
# boards manager not working on 1.6.7 - 1.6.8
#  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
# install lib EnableInterrupt Low-Power
  - arduino --install-library "EnableInterrupt"
  - arduino --install-library "Low-Power"
#  - git clone https://github.com/bblanchon/ArduinoJson /usr/local/share/arduino/libraries/ArduinoJson
#  - arduino --install-boards esp8266:esp8266
#  - arduino --board esp8266:esp8266:generic --save-prefs
#  - arduino --pref "compiler.warning_level=all" --save-prefs
  - arduino --pref "update.check=false" --save-prefs
script:
  - "echo $PWD"
  - "echo $HOME"
  - "ls $PWD"
  - arduino --verify --board arduino:avr:pro:cpu=8MHzatmega328 $PWD/examples/HM-RC-4/HM-RC-4.ino
notifications:
  email:
    on_success: change
    on_failure: change
