language: c++
env:
  global:
    - IDE_VERSION=1.8.1
    - BOARDSTM="stm32duino:STM32F1:mapleMini"
    - BOARD644="MightyCore:avr:644:pinout=bobuino,variant=modelP,LTO=Os,clock=8MHz_internal"
    - BOARD328P="arduino:avr:pro:cpu=8MHzatmega328"
    - BOARD=$BOARD328P
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
#  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
#      arduino --install-boards arduino:samd;
#    fi
#  - buildSketch() { arduino --verify --board $BOARD $SKETCHPATH/$1/$1.ino 2>&1 | tee /tmp/$1.log; cat /tmp/$1.log; }
  - buildSketch() { arduino --verify --board $BOARD $SKETCHPATH/$1/$1.ino; }
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
  - arduino --install-library "OneWire"
  - git clone https://github.com/GreyGnome/EnableInterrupt $HOME/arduino-ide/libraries/EnableInterrupt
  - git clone https://github.com/rocketscream/Low-Power.git $HOME/arduino-ide/libraries/Low-Power
  - git clone https://github.com/adafruit/TSL2561-Arduino-Library $HOME/arduino-ide/libraries/TSL2561-Arduino-Library
  - git clone https://github.com/spease/Sensirion.git $HOME/arduino-ide/libraries/Sensirion
  - git clone https://github.com/finitespace/BME280.git  $HOME/arduino-ide/libraries/BME280
  - git clone https://github.com/xoseperez/hlw8012.git  $HOME/arduino-ide/libraries/hlw8012
# Sketches from Jerome to test
  - git clone https://github.com/jp112sdl/Beispiel_AskSinPP.git $HOME/Beispiel_AskSinPP
  - git clone https://github.com/jp112sdl/HB-UNI-Sen-LEV-US.git $HOME/Beispiel_AsksinPP/HB-UNI-Sen-LEV-US
  - git clone https://github.com/jp112sdl/HB-UNI-Sen-DIST-US.git $HOME/Beispiel_AsksinPP/HB-UNI-Sen-DIST-US
# setup arduino IDE
  - arduino --pref "update.check=false" --save-prefs
  - arduino --pref "boardsmanager.additional.urls=http://dan.drown.org/stm32duino/package_STM32duino_index.json,https://mcudude.github.io/MightyCore/package_MCUdude_MightyCore_index.json" --save-prefs
  - arduino --install-boards stm32duino:STM32F1:2017.9.5
  - arduino --install-boards MightyCore:avr:2.0.1
  - echo "compiler.cpp.extra_flags=-DUSE_AES -DHM_DEF_KEY=0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,0x10 -DHM_DEF_KEY_INDEX=0" >$HOME/arduino-ide/hardware/arduino/avr/platform.local.txt
script:
#  - "echo $PWD"
#  - "echo $HOME"
#  - "ls $PWD"
#  - buildSketch HM-DW-WM
#  - buildSketch HM-LC-SWX-SM
  - export BOARD=$BOARD328P
  - export SKETCHPATH=$PWD/examples
  - buildSketch FreqTest
  - buildSketch HM-ES-TX-WM
  - buildSketch HM-LC-Bl1-FM
  - buildSketch HM-LC-Dim1PWM-CV
  - buildSketch HM-LC-SW1-BA-PCB
  - buildSketch HM-LC-SWX-SM
  - buildSketch HM-RC-4
  - buildSketch HM-RC-8
  - buildSketch HM-RC-P1
  - buildSketch HM-SEC-MDIR
  - buildSketch HM-SEC-RHS
  - buildSketch HM-SEC-SD
  - buildSketch HM-SEC-WDS
  - buildSketch HM-SEN-MDIR-WM55
  - buildSketch HM-WDS10-TH-O
  - buildSketch HM-WDS100-C6-O-2
  - buildSketch HM-LC-DW-WM
  - buildSketch HM-DW-WM
  - export SKETCHPATH=$PWD/examples/custom
  - buildSketch HB-GEN-SENS
  - buildSketch HB-IBUT-8
  - buildSketch HB-RC-3-ENC
  - buildSketch HB-SW2-SENS
  - export SKETCHPATH=$HOME/Beispiel_AskSinPP/examples
  - buildSketch HB-LC-Bl1PBU-FM
  - buildSketch HB-LC-SW12-FM
  - buildSketch HB-LC-Sw1PBU-FM
  - buildSketch HB-LC-Sw2PBU-FM
  - buildSketch HM-CC-SCD
  - buildSketch HM-Dis-TD-T
#  - buildSketch HM-Dis-WM55
  - export BOARD=$BOARD644
  - buildSketch HM-ES-PMSw1-Pl
  - buildSketch HM-ES-PMSw1-Pl_GosundSP1
  - export BOARD=$BOARD328P
  - buildSketch HM-ES-TX-WM_CCU
  - buildSketch HM-LC-SW1-FM_Shelly1
  - buildSketch HM-LC-SW1-SM_SONOFF_BASIC
  - buildSketch HM-LC-Sw1-Pl-CT-R1
  - buildSketch HM-LC-Sw1-Pl-DN-R1
  - buildSketch HM-LC-Sw1-Pl-DN-R1_OBI
  - buildSketch HM-LC-Sw2-FM
  - buildSketch HM-MOD-Re-8
  - buildSketch HM-PB-2-FM
  - buildSketch HM-PB-2-WM55
  - buildSketch HM-PB-6-WM55
  - buildSketch HM-PB-MP-WM
  - buildSketch HM-PBI-4-FM
  - buildSketch HM-RC-2-PBU-FM
  - buildSketch HM-SCI-3-FM
  - buildSketch HM-SEC-SC
  - buildSketch HM-SEC-SCO
  - buildSketch HM-Sec-TiS
  - buildSketch HM-Sen-DB-PCB
  - buildSketch HM-Sen-LI-O
  - buildSketch HM-Sen-WA-OD
  - buildSketch HM-WDS30-OT2-DS18B20
  - buildSketch HM-WDS30-OT2-NTC
  - buildSketch HM-WDS30-T-O-NTC
  - buildSketch HM-WDS40-TH-I-BME280
#  - buildSketch HM-WDS40-TH-I-DHT22
#  - buildSketch HM-WDS40-TH-I-DS18B20
  - buildSketch HM-WDS40-TH-I-SHT10
# more homebrew devices
  - buildSketch HB-UNI-Sen-LEV-US
  - buildSketch HB-UNI-Sen-DIST-US
notifications:
  email:
    on_success: change
    on_failure: change
